//! `.pltx` container format — a ZIP, Word-style.
//!
//! A `.pltx` bundles the document source, the cell results and the ENTIRE
//! working directory of the project — the `.build.tex` copies, the engine's
//! scratch (.aux, .log, .toc, .out, .mtc*, .fls, .maf…), the SyncTeX index and
//! the PDF. None of that is ever written next to the document.
//!
//! The result is a project folder that holds only what the author put in it:
//! the `.pltx` files, their images and their `.sty` packages. Same idea as a
//! `.docx`, which does not scatter its rendering scratch beside itself.
//!
//! Layout inside the zip:
//!   manifest.json          {"format":"pyx-pltx","version":1}
//!   source.tex             the editable LaTeX + %#python cells (UTF-8)
//!   outputs.json           (optional) the cells' last results, so reopening a
//!                          report SHOWS its numbers, tables and figures
//!                          without re-running anything (see cell-outputs.js)
//!   build/<path>           (optional) the project's whole working directory,
//!                          subfolders preserved
//!
//! Backward compatible: a legacy plain-text `.pltx` (not a zip) still opens —
//! `read` reports `is_zip=false` and the JS side decodes it as text. Older zip
//! containers carried a few loose artifacts at the top level instead; they are
//! simply ignored, and the next save writes the current layout.

use crate::workspace;
use std::fs;
use std::io::{Read, Write};
use std::path::Path;

const SOURCE_ENTRY: &str = "source.tex";
const OUTPUTS_ENTRY: &str = "outputs.json";
const MANIFEST_ENTRY: &str = "manifest.json";
const MANIFEST_BODY: &str = "{\"format\":\"pyx-pltx\",\"version\":1}";
/// Prefix for the working-directory entries.
const BUILD_PREFIX: &str = "build/";

#[derive(serde::Serialize)]
pub struct PltxRead {
    pub is_zip: bool,
    pub source: Option<String>,
    /// Serialized cell results stored with the document, if any.
    pub outputs: Option<String>,
}

fn is_zip(bytes: &[u8]) -> bool {
    bytes.len() >= 4 && &bytes[0..2] == b"PK" && (bytes[2] == 3 || bytes[2] == 5 || bytes[2] == 7)
}

/// Reject an entry name that would escape the working directory.
fn safe_rel(name: &str) -> Option<&str> {
    let rel = name.strip_prefix(BUILD_PREFIX)?;
    if rel.is_empty() || rel.ends_with('/') {
        return None;
    }
    let bad = rel.split('/').any(|seg| seg.is_empty() || seg == ".." || seg == ".")
        || rel.contains('\\')
        || Path::new(rel).is_absolute();
    if bad { None } else { Some(rel) }
}

/// Extensions an earlier version of Pyx (or a run in another editor) may have
/// left beside the document. All of them are regenerated by the next compile.
const LEGACY_EXT: &[&str] = &[
    ".build.tex", ".aux", ".log", ".toc", ".out", ".lof", ".lot", ".fls",
    ".fdb_latexmk", ".synctex.gz", ".maf", ".nav", ".snm", ".vrb", ".bbl", ".blg",
];

/// Remove the build leftovers of THIS document from the user's folder.
///
/// Versions before this one wrote the engine's scratch next to the document,
/// and 1.2.1 put it in a `.pyxbuild` folder there. Neither should exist any
/// more, but upgrading does not tidy a folder by itself — so opening a document
/// does.
///
/// Deliberately narrow: only `<this document's stem><known extension>` and the
/// `.pyxbuild` folder. A file that merely shares an extension with a build
/// artifact but not the document's name is somebody else's and is left alone.
fn tidy_legacy(doc: &Path) {
    let dir = match doc.parent() { Some(d) => d, None => return };
    let stem = match doc.file_stem() { Some(s) => s.to_string_lossy().to_string(), None => return };
    for ext in LEGACY_EXT {
        let _ = fs::remove_file(dir.join(format!("{stem}{ext}")));
    }
    // minitoc writes one file per chapter: <stem>.mtc, .mtc0, .mtc1, …
    if let Ok(rd) = fs::read_dir(dir) {
        for e in rd.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            let is_mtc = name
                .strip_prefix(&format!("{stem}.mtc"))
                .map(|r| r.is_empty() || r.chars().all(|c| c.is_ascii_digit()))
                .unwrap_or(false);
            if is_mtc {
                let _ = fs::remove_file(e.path());
            }
        }
    }
    let _ = fs::remove_dir_all(dir.join(".pyxbuild"));
}

/// Read a `.pltx`: its source and saved cell results. If it is legacy plain
/// text, report `is_zip=false`.
///
/// `restore` also unpacks the saved working directory, so the first compile
/// after OPENING a document reuses its cross-references and its PDF can be shown
/// at once. It must be true ONLY when a document is opened for editing.
///
/// It used to happen on every read, and the compiler reads `.pltx` files all
/// the time — the root of a child being edited, every chapter, every candidate
/// when it searches a folder for the root. Each of those reads overwrote the
/// working directory with the copy from the LAST SAVE: the `.build.tex` files
/// the compile had just written were replaced by stale ones, and the engine
/// typeset the old text. Edits intermittently vanished from the PDF.
pub fn read(path: &str, restore: bool) -> Result<PltxRead, String> {
    let bytes = fs::read(path).map_err(|e| format!("No se pudo leer {path}: {e}"))?;
    if restore {
        // Whatever an older version scattered beside this document goes now.
        tidy_legacy(Path::new(path));
    }
    if !is_zip(&bytes) {
        return Ok(PltxRead { is_zip: false, source: None, outputs: None });
    }

    let mut zip = zip::ZipArchive::new(std::io::Cursor::new(&bytes))
        .map_err(|e| format!("El .pltx está dañado: {e}"))?;

    let mut source = String::new();
    if let Ok(mut f) = zip.by_name(SOURCE_ENTRY) {
        f.read_to_string(&mut source)
            .map_err(|e| format!("No se pudo leer la fuente del .pltx: {e}"))?;
    } else {
        return Err("El .pltx no contiene source.tex".into());
    }

    // The saved cell results. Absent in older documents and in documents saved
    // with result storage turned off — both are normal, not an error.
    let mut outputs = None;
    if let Ok(mut f) = zip.by_name(OUTPUTS_ENTRY) {
        let mut buf = String::new();
        if f.read_to_string(&mut buf).is_ok() && !buf.is_empty() {
            outputs = Some(buf);
        }
    }

    // Restore the working directory (best-effort: a failure here costs one
    // extra compile pass, never the document).
    let names: Vec<String> = (0..zip.len())
        .filter_map(|i| zip.name_for_index(i).map(str::to_string))
        .filter(|n| restore && n.starts_with(BUILD_PREFIX))
        .collect();
    if !names.is_empty() {
        // When the document itself was last written. Anything in the working
        // directory NEWER than that came from a compile after the save — and
        // saving packs the working directory BEFORE the compile it triggers
        // runs, so the zip always holds the build from one edit earlier.
        // Restoring over those files replaced the latest PDF with the previous
        // one, and reopening a document showed it an edit behind.
        let saved_at = fs::metadata(path).and_then(|m| m.modified()).ok();
        if let Ok(root) = workspace::ensure_build_dir(path) {
            for name in names {
                let rel = match safe_rel(&name) {
                    Some(r) => r.to_string(),
                    None => continue,
                };
                let dest = root.join(&rel);
                let newer_here = match (saved_at, dest.metadata().and_then(|m| m.modified()).ok()) {
                    (Some(saved), Some(here)) => here > saved,
                    _ => false,
                };
                if newer_here {
                    continue;
                }
                if let Ok(mut f) = zip.by_name(&name) {
                    let mut buf = Vec::new();
                    if f.read_to_end(&mut buf).is_ok() {
                        if let Some(parent) = dest.parent() {
                            let _ = fs::create_dir_all(parent);
                        }
                        let _ = fs::write(dest, &buf);
                    }
                }
            }
        }
    }

    Ok(PltxRead { is_zip: true, source: Some(source), outputs })
}

/// Save a `.pltx`: source + cell results + the project's whole working
/// directory, written to a temp file and renamed so a crash mid-write can never
/// corrupt the document.
///
/// The working directory is NOT deleted afterwards: it lives outside the
/// user's folder, it is invisible, and keeping it is what lets the next compile
/// reuse the engine's cross-reference state instead of starting from zero.
/// Payloads that are already compressed, so the zip stores them verbatim.
fn precompressed(rel: &str) -> bool {
    matches!(
        rel.rsplit('.').next().map(str::to_ascii_lowercase).as_deref(),
        Some("pdf" | "png" | "jpg" | "jpeg" | "gif" | "webp" | "gz" | "zip" | "xz" | "7z")
    )
}

pub fn write(path: &str, source: &str, outputs: Option<&str>) -> Result<(), String> {
    let p = Path::new(path);
    let tmp = p.with_extension("pltx.tmp");
    {
        let file = fs::File::create(&tmp)
            .map_err(|e| format!("No se pudo escribir el .pltx: {e}"))?;
        let mut zip = zip::ZipWriter::new(file);
        let deflate: zip::write::FileOptions<'_, ()> =
            zip::write::FileOptions::default().compression_method(zip::CompressionMethod::Deflated);
        let store: zip::write::FileOptions<'_, ()> =
            zip::write::FileOptions::default().compression_method(zip::CompressionMethod::Stored);

        let mut put = |name: &str,
                       data: &[u8],
                       opts: zip::write::FileOptions<'_, ()>|
         -> Result<(), String> {
            zip.start_file(name, opts).map_err(|e| format!("zip: {e}"))?;
            zip.write_all(data).map_err(|e| format!("zip: {e}"))?;
            Ok(())
        };
        put(MANIFEST_ENTRY, MANIFEST_BODY.as_bytes(), deflate)?;
        put(SOURCE_ENTRY, source.as_bytes(), deflate)?;
        if let Some(o) = outputs.filter(|o| !o.is_empty()) {
            put(OUTPUTS_ENTRY, o.as_bytes(), deflate)?;
        }
        for (rel, abs) in workspace::walk(&workspace::build_dir(path)) {
            if let Ok(data) = fs::read(&abs) {
                // The text of a build directory (.aux, .log, .toc) deflates to
                // a fraction of its size and is worth compressing. The PDF and
                // the figures are ALREADY compressed: re-deflating them costs
                // most of the save on a figure-heavy report and buys nothing.
                let opts = if precompressed(&rel) { store } else { deflate };
                put(&format!("{BUILD_PREFIX}{rel}"), &data, opts)?;
            }
        }
        zip.finish().map_err(|e| format!("zip: {e}"))?;
    }
    fs::rename(&tmp, p).map_err(|e| format!("No se pudo guardar el .pltx: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// THE regression behind "I edit, I compile, and the PDF does not change".
    ///
    /// The compiler reads `.pltx` files constantly — the root of the chapter
    /// being edited, every chapter, every candidate while it looks for the
    /// root. When every read also restored the saved working directory, each of
    /// those reads put the LAST SAVE's `.build.tex` back on top of the one the
    /// compile had just written, and the engine typeset stale text.
    #[test]
    fn only_opening_restores_the_working_directory() {
        let dir = std::env::temp_dir().join(format!("pyx-pltx-test-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let doc = dir.join("_Proyecto.pltx");
        let doc = doc.to_str().unwrap();
        let work = workspace::ensure_build_dir(doc).unwrap();
        let build = work.join("_Proyecto.build.tex");

        // Saved with the OLD build in its working directory…
        fs::write(&build, "VERSION GUARDADA").unwrap();
        write(doc, r"\documentclass{article}", None).unwrap();
        // …then the compile the save triggered writes the NEW one. (The pause
        // keeps the two timestamps apart on a coarse system clock; a real
        // compile ends seconds after the save.)
        std::thread::sleep(std::time::Duration::from_millis(60));
        fs::write(&build, "VERSION RECIEN COMPILADA").unwrap();

        // A compile-time read must leave it alone.
        let r = read(doc, false).unwrap();
        assert!(r.is_zip);
        assert_eq!(r.source.as_deref(), Some(r"\documentclass{article}"));
        assert_eq!(fs::read_to_string(&build).unwrap(), "VERSION RECIEN COMPILADA");

        // Opening keeps it too: it is NEWER than the saved document, so it is
        // the latest build, and the zip only has the one from before the save.
        read(doc, true).unwrap();
        assert_eq!(fs::read_to_string(&build).unwrap(), "VERSION RECIEN COMPILADA");

        // But a working file OLDER than the document is stale — left by some
        // other version of it — and opening brings back what was saved.
        let old = std::time::SystemTime::now() - std::time::Duration::from_secs(3600);
        fs::write(&build, "VERSION VIEJA DE OTRA COPIA").unwrap();
        fs::File::options().write(true).open(&build).unwrap().set_modified(old).unwrap();
        read(doc, true).unwrap();
        assert_eq!(fs::read_to_string(&build).unwrap(), "VERSION GUARDADA");

        let _ = fs::remove_dir_all(&work);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn already_compressed_payloads_are_stored_not_deflated() {
        for f in ["main.pdf", "cap/fig.PNG", "x.synctex.gz", "a.jpeg"] {
            assert!(precompressed(f), "{f}");
        }
        for f in ["main.aux", "main.log", "cap/uno.build.tex", "main.toc", "sinextension"] {
            assert!(!precompressed(f), "{f}");
        }
    }
}
